org: knative
repo: client
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20241026-10422e45a
cluster: prow-build

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]

  - name: integration-tests-latest-release
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-integration-tests-latest-release.sh]

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: tekton
    types: [periodic]
    command: [runner.sh, ./test/tekton-tests.sh]

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release,
      --apple-codesign-key, /etc/notary/cert.p12,
      --apple-notary-api-key, /etc/notary/key.json,
      --apple-codesign-password-file, /etc/notary/password]
    requirements: [nightly-notary]
    excluded_requirements: [gcp]
    max_concurrency: 1
    reporter_config:
      slack:
        channel: knative-client
        report_template: |
          "The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"
  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/client, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token,
      --apple-codesign-key, /etc/notary/cert.p12,
      --apple-notary-api-key, /etc/notary/key.json,
      --apple-codesign-password-file, /etc/notary/password]
    requirements: [release-notary]
    excluded_requirements: [gcp]
    max_concurrency: 1
