org: knative
repo: eventing
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20240213-74adf2624

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    resources: default
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: conformance-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-conformance-tests.sh]

  - name: reconciler-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-rekt-tests.sh]

  - name: upgrade-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-upgrade-tests.sh]

  - name: continuous
    types: [periodic]
    timeout: 3h
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: nightly
    types: [periodic]
    timeout: 4h
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly]
    excluded_requirements: [gcp]
    max_concurrency: 1
    reporter_config:
      slack:
        channel: knative-eventing
        report_template: |
          "The nightly release has failed, please check the logs: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"

  - name: release
    types: [periodic]
    timeout: 4h
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/eventing, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release]
    excluded_requirements: [gcp]
    max_concurrency: 1

resources: high
resources_presets:
  high:
    limits:
      memory: 16Gi
    requests:
      memory: 12Gi

  default:
    limits:
      memory: 10Gi
    requests:
      memory: 8Gi
