org: knative
repo: serving
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20260203-cb80c9185
requirements: [docker]

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    resources: default
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: upgrade-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-upgrade-tests.sh]

  - name: istio-latest-no-mesh
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh --istio-version latest --no-mesh"]

  - name: istio-latest-no-mesh-tls
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-external-domain-tls-tests.sh --istio-version latest --no-mesh"]

  - name: performance-tests
    timeout: 3h
    types: [presubmit]
    requirements: [perf]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/performance/performance-tests.sh]
    modifiers: [presubmit_optional, presubmit_skipped]

  - name: istio-latest-mesh
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh --istio-version latest --mesh"]
    modifiers: [presubmit_optional, presubmit_skipped]

  - name: istio-latest-mesh-short
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh --istio-version latest --mesh --short"]
    modifiers: [presubmit_optional, presubmit_skipped]

  - name: istio-latest-mesh-tls
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-external-domain-tls-tests.sh --istio-version latest --mesh"]
    modifiers: [presubmit_optional, presubmit_skipped]

  - name: kourier-stable
    types: [presubmit]
    regex: ^third_party/kourier-latest/*
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh --kourier-version stable"]
    modifiers: [presubmit_skipped]

  - name: kourier-stable-tls
    types: [presubmit]
    regex: ^third_party/kourier-latest/*
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-external-domain-tls-tests.sh --kourier-version stable"]
    modifiers: [presubmit_skipped]

  - name: contour-latest
    types: [presubmit]
    regex: ^third_party/contour-latest/*
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh --contour-version latest"]
    modifiers: [presubmit_skipped]

  - name: contour-tls
    types: [presubmit]
    regex: ^third_party/contour-latest/*
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-external-domain-tls-tests.sh --contour-version latest"]
    modifiers: [presubmit_skipped]

  - name: gateway-api-latest
    types: [presubmit]
    regex: ^third_party/gateway-api-latest/*
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh --gateway-api-version latest"]
    modifiers: [presubmit_skipped]

  - name: gateway-api-latest-and-contour
    types: [presubmit]
    regex: ^third_party/gateway-api-latest/*
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh --gateway-api-version latest --gateway-api-implementation contour"]
    modifiers: [presubmit_optional, presubmit_skipped]

  - name: https
    types: [presubmit]
    regex: ^third_party/cert-manager-latest/*
    command:
    - runner.sh
    args:
    - ./test/presubmit-tests.sh
    - --run-test
    - "./test/e2e-tests.sh --https"
    - --run-test
    - "./test/e2e-external-domain-tls-tests.sh --https"
    modifiers: [presubmit_optional, presubmit_skipped]

  - name: continuous
    timeout: 3h
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: istio-latest-mesh
    types: [periodic]
    timeout: 5h
    command:
    - runner.sh
    args:
    - ./test/presubmit-tests.sh
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest --mesh
    - --run-test
    - ./test/e2e-external-domain-tls-tests.sh --istio-version latest --mesh

  - name: istio-latest-no-mesh
    types: [periodic]
    timeout: 5h
    command:
    - runner.sh
    args:
    - ./test/presubmit-tests.sh
    - --run-test
    - ./test/e2e-tests.sh --istio-version latest --no-mesh
    - --run-test
    - ./test/e2e-external-domain-tls-tests.sh --istio-version latest --no-mesh

  - name: kourier-stable
    types: [periodic]
    timeout: 5h
    command:
    - runner.sh
    args:
    - ./test/presubmit-tests.sh
    - --run-test
    - ./test/e2e-tests.sh --kourier-version stable
    - --run-test
    - ./test/e2e-external-domain-tls-tests.sh --kourier-version stable --run-http01-external-domain-tls-tests

  - name: contour-latest
    types: [periodic]
    timeout: 5h
    command:
    - runner.sh
    args:
    - ./test/presubmit-tests.sh
    - --run-test
    - ./test/e2e-tests.sh --contour-version latest
    - --run-test
    - ./test/e2e-external-domain-tls-tests.sh --contour-version latest --run-http01-external-domain-tls-tests

  - name: gateway-api-istio
    types: [periodic]
    timeout: 5h
    command:
    - runner.sh
    args:
    - ./test/presubmit-tests.sh
    - --run-test
    - ./test/e2e-tests.sh --gateway-api-version latest

  - name: gateway-api-contour
    types: [periodic]
    timeout: 5h
    command:
    - runner.sh
    args:
    - ./test/presubmit-tests.sh
    - --run-test
    - ./test/e2e-tests.sh --gateway-api-version latest --gateway-api-implementation contour

  - name: https
    types: [periodic]
    timeout: 5h
    command:
    - runner.sh
    args:
    - ./test/presubmit-tests.sh
    - --run-test
    - ./test/e2e-tests.sh --https
    - --run-test
    - ./test/e2e-external-domain-tls-tests.sh --https

  - name: performance-tests
    timeout: 5h
    types: [periodic]
    requirements: [perf]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/performance/performance-tests.sh]

  - name: nightly
    types: [periodic]
    timeout: 5h
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly]
    excluded_requirements: [gcp]
    max_concurrency: 1
    reporter_config:
      slack:
        channel: knative-serving
        report_template: |
          "[serving] nightly release job fails, check the log: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"

  - name: release
    types: [periodic]
    timeout: 3h
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/serving, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release]
    excluded_requirements: [gcp]
    max_concurrency: 1

resources: high
resources_presets:
  high:
    limits:
      memory: 16Gi
    requests:
      memory: 12Gi

  default:
    limits:
      memory: 10Gi
    requests:
      memory: 8Gi

requirement_presets:
  nightly:
    podSpec:
      serviceAccountName: nightly
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/nightly-account/service-account.json
      - name: SIGN_IMAGES
        value: "true"
      - name: ATTEST_IMAGES
        value: "true"
    volumeMounts:
      - name: nightly-account
        mountPath: /etc/nightly-account
        readOnly: true
    volumes:
      - name: nightly-account
        secret:
          items:
          - key: nightly.json
            path: service-account.json
          secretName: prow-google-credentials

  release:
    podSpec:
      serviceAccountName: release
    env:
      - name: SIGN_IMAGES
        value: "true"
      - name: ATTEST_IMAGES
        value: "true"
    volumeMounts:
      - name: hub-token
        mountPath: /etc/hub-token
        readOnly: true
    volumes:
      - name: hub-token
        secret:
          items:
          - key: hub_token
            path: token
          secretName: github-credentials
      - name: release-account
        secret:
          items:
          - key: release.json
            path: service-account.json
          secretName: prow-google-credentials

  perf:
    podSpec:
      serviceAccountName: test-runner
    volumeMounts:
      - name: influx-token-secret-volume
        mountPath: /etc/influx-token-secret-volume
        readOnly: true
      - name: influx-url-secret-volume
        mountPath: /etc/influx-url-secret-volume
        readOnly: true
    volumes:
      - name: influx-token-secret-volume
        secret:
          secretName: influx-token-secret
          defaultMode: 0600
      - name: influx-url-secret-volume
        secret:
          secretName: influx-url-secret
          defaultMode: 0600
  gcp:
    podSpec:
      serviceAccountName: test-runner
