org: knative
repo: toolbox
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20250307-bc85e28e0

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]
