org: knative-extensions
repo: backstage-plugins
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20250516-ab11990bb

jobs:

  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [ presubmit ]
    resources: default
    command: [ runner.sh, ./test/presubmit-tests.sh, --unit-tests ]
    excluded_requirements: [ gcp ]

  - name: e2e-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-tests.sh]

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]
    requirements: [docker]

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly, docker]
    excluded_requirements: [gcp]
    max_concurrency: 1

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/backstage-plugins, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release, docker]
    excluded_requirements: [gcp]
    max_concurrency: 1

resources: default
resources_presets:
  default:
    limits:
      memory: 10Gi
    requests:
      memory: 8Gi
