org: knative-extensions
repo: eventing-kafka-broker
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20240213-74adf2624

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]
    requirements: [docker]
    env:
      - name: BROKER_CLASS
        value: Kafka

  - name: upgrade-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/upgrade-tests.sh"]
    requirements: [docker]
    env:
      - name: BROKER_CLASS
        value: Kafka

  - name: reconciler-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/reconciler-tests.sh"]
    requirements: [docker]
    env:
      - name: BROKER_CLASS
        value: Kafka
  
  - name: reconciler-tests-loom
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/reconciler-tests.sh"]
    requirements: [docker]
    modifiers: [presubmit_optional, presubmit_skipped]
    env:
      - name: BROKER_CLASS
        value: Kafka
      - name: USE_LOOM
        value: "true"

  - name: reconciler-tests-namespaced-broker
    types: [ presubmit ]
    command: [ runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/reconciler-tests.sh" ]
    requirements: [ docker ]
    env:
      - name: BROKER_CLASS
        value: KafkaNamespaced

  - name: reconciler-tests-namespaced-broker-loom
    types: [ presubmit ]
    command: [ runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/reconciler-tests.sh" ]
    requirements: [ docker ]
    modifiers: [presubmit_optional, presubmit_skipped]
    env:
      - name: BROKER_CLASS
        value: KafkaNamespaced
      - name: USE_LOOM
        value: "true"

  - name: reconciler-tests-keda
    types: [ presubmit ]
    command: [ runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/keda-reconciler-tests.sh"]
    requirements: [ docker ]
    env:
      - name: BROKER_CLASS
        value: Kafka

  - name: channel-integration-tests-ssl
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh"]
    requirements: [docker]
    env:
      - name: EVENTING_KAFKA_BROKER_CHANNEL_AUTH_SCENARIO
        value: SSL
      - name: BROKER_CLASS
        value: Kafka

  - name: channel-integration-tests-sasl-ssl
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh"]
    requirements: [docker]
    env:
      - name: EVENTING_KAFKA_BROKER_CHANNEL_AUTH_SCENARIO
        value: SASL_SSL
      - name: BROKER_CLASS
        value: Kafka

  - name: channel-integration-tests-sasl-plain
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/e2e-tests.sh"]
    requirements: [docker]
    env:
      - name: EVENTING_KAFKA_BROKER_CHANNEL_AUTH_SCENARIO
        value: SASL_PLAIN
      - name: BROKER_CLASS
        value: Kafka

  - name: channel-reconciler-tests-ssl
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/reconciler-tests.sh"]
    requirements: [docker]
    env:
      - name: EVENTING_KAFKA_BROKER_CHANNEL_AUTH_SCENARIO
        value: SSL
      - name: BROKER_CLASS
        value: Kafka

  - name: channel-reconciler-tests-sasl-ssl
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/reconciler-tests.sh"]
    requirements: [docker]
    env:
      - name: EVENTING_KAFKA_BROKER_CHANNEL_AUTH_SCENARIO
        value: SASL_SSL
      - name: BROKER_CLASS
        value: Kafka

  - name: channel-reconciler-tests-sasl-plain
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, "./test/reconciler-tests.sh"]
    requirements: [docker]
    env:
      - name: EVENTING_KAFKA_BROKER_CHANNEL_AUTH_SCENARIO
        value: SASL_PLAIN
      - name: BROKER_CLASS
        value: Kafka

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]
    requirements: [docker]
    env:
      - name: BROKER_CLASS
        value: Kafka

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly, docker]
    excluded_requirements: [gcp]
    max_concurrency: 1
    reporter_config:
      slack:
        channel: knative-eventing
        report_template: |
          "The nightly release job has failed, check the log: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"
    env:
      - name: BROKER_CLASS
        value: Kafka

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/eventing-kafka-broker, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release, docker]
    excluded_requirements: [gcp]
    max_concurrency: 1
    env:
      - name: BROKER_CLASS
        value: Kafka
