org: knative-extensions
repo: eventing-integrations
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20250116-9d03c2241

jobs:

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly, docker]
    excluded_requirements: [gcp]
    max_concurrency: 1
