org: knative-extensions
repo: reconciler-test
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20251211-ce6d6c676

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]
